/// Flutter icons GoogleSearchClone
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  GoogleSearchClone
///      fonts:
///       - asset: fonts/GoogleSearchClone.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class GoogleSearchClone {
  GoogleSearchClone._();

  static const _kFontFam = 'GoogleSearchClone';
  static const String? _kFontPkg = null;

  static const IconData moreApps = IconData(0xe82f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData searchIcon = IconData(0xe830, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData micIcon = IconData(0xe831, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
